services:
  cloud:
    build: ./packages/cloud
    restart: always
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:8
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo:/data/db

  nginx:
    image: nginx:1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/nginx/ssl/certs:/etc/ssl/certs/
      - ./config/nginx/ssl/private:/etc/ssl/private
    depends_on:
      - cloud
      - web

  redis:
    image: redis:8
    restart: always
    volumes:
      - redis:/data

  web:
    build: ./packages/web
    restart: always

volumes:
  mongo:
  redis:

networks:
  default:
    name: spatial
