// Copyright © Spatial. All rights reserved.

namespace Ignite.Contracts;

/// <summary>
/// Specifies the class of an item.
/// </summary>
public enum ItemClassEnum
{
    ITEMCLASS_BYTELOT = 0x0,
    ITEMCLASS_WORDLOT = 0x1,
    ITEMCLASS_DWRDLOT = 0x2,
    ITEMCLASS_QUESTITEM = 0x3,
    ITEMCLASS_AMULET = 0x4,
    ITEMCLASS_WEAPON = 0x5,
    ITEMCLASS_ARMOR = 0x6,
    ITEMCLASS_SHIELD = 0x7,
    ITEMCLASS_BOOT = 0x8,
    ITEMCLASS_FURNITURE = 0x9,
    ITEMCLASS_DECORATION = 0xA,
    ITEMCLASS_SKILLSCROLL = 0xB,
    ITEMCLASS_RECALLSCROLL = 0xC,
    ITEMCLASS_BINDITEM = 0xD,
    ITEMCLASS_UPSOURCE = 0xE,
    ITEMCLASS_ITEMCHEST = 0xF,
    ITEMCLASS_WTLICENCE = 0x10,
    ITEMCLASS_KQ = 0x11,
    ITEMCLASS_HOUSESKIN = 0x12,
    ITEMCLASS_UPRED = 0x13,
    ITEMCLASS_UPBLUE = 0x14,
    ITEMCLASS_KQSTEP = 0x15,
    ITEMCLASS_FEED = 0x16,
    ITEMCLASS_RIDING = 0x17,
    ITEMCLASS_AMOUNT = 0x18,
    ITEMCLASS_UPGOLD = 0x19,
    ITEMCLASS_COSWEAPON = 0x1A,
    ITEMCLASS_ACTIONITEM = 0x1B,
    ITEMCLASS_GBCOIN = 0x1C,
    ITEMCLASS_CAPSULE = 0x1D,
    ITEMCLASS_CLOSEDCARD = 0x1E,
    ITEMCLASS_OPENCARD = 0x1F,
    ITEMCLASS_MONEY = 0x20,
    ITEMCLASS_NOEFFECT = 0x21,
    ITEMCLASS_ENCHANT = 0x22,
    ITEMCLASS_ACTIVESKILL = 0x23,
    ITEMCLASS_PUP = 0x24,
    ITEMCLASS_COSSHIELD = 0x25,
    ITEMCLASS_BRACELET = 0x26,
    MAX_ITEMCLASSENUM = 0x27
}