// Copyright © Spatial. All rights reserved.

namespace Ignite.Contracts;

/// <summary>
/// The index of an SHN file in <see cref="Maps.PROTO_NC_MAP_LOGIN_REQ"/>.
/// </summary>
public enum SHN_DATA_FILE_INDEX
{
  SHN_Abstate = 0x0,
  SHN_ActiveSkill = 0x1,
  SHN_CharacterTitleData = 0x2,
  SHN_ChargedEffect = 0x3,
  SHN_ClassName = 0x4,
  SHN_Gather = 0x5,
  SHN_GradeItemOption = 0x6,
  SHN_ItemDismantle = 0x7,
  SHN_ItemInfo = 0x8,
  SHN_MapInfo = 0x9,
  SHN_MiniHouse = 0xA,
  SHN_MiniHouseFurniture = 0xB,
  SHN_MiniHouseObjAni = 0xC,
  SHN_MobInfo = 0xD,
  SHN_PassiveSkill = 0xE,
  SHN_Riding = 0xF,
  SHN_SubAbstate = 0x10,
  SHN_UpgradeInfo = 0x11,
  SHN_WeaponAttrib = 0x12,
  SHN_WeaponTitleData = 0x13,
  SHN_MiniHouseFurnitureObjEffect = 0x14,
  SHN_MiniHouseFurnitureEndure = 0x15,
  SHN_DiceDividind = 0x16,
  SHN_ActionViewInfo = 0x17,
  SHN_MapLinkPoint = 0x18,
  SHN_MapWayPoint = 0x19,
  SHN_AbStateView = 0x1A,
  SHN_ActiveSkillView = 0x1B,
  SHN_CharacterTitleStateView = 0x1C,
  SHN_EffectViewInfo = 0x1D,
  SHN_ItemShopView = 0x1E,
  SHN_ItemViewInfo = 0x1F,
  SHN_MapViewInfo = 0x20,
  SHN_MobViewInfo = 0x21,
  SHN_NPCViewInfo = 0x22,
  SHN_PassiveSkillView = 0x23,
  SHN_ProduceView = 0x24,
  SHN_CollectCardView = 0x25,
  SHN_GTIView = 0x26,
  SHN_ItemViewEquipTypeInfo = 0x27,
  SHN_SingleData = 0x28,
  SHN_MarketSearchInfo = 0x29,
  SHN_ItemMoney = 0x2A,
  SHN_PupMain = 0x2B,
  SHN_ChatColor = 0x2C,
  SHN_TermExtendMatch = 0x2D,
  SHN_MinimonInfo = 0x2E,
  SHN_MinimonAutoUseItem = 0x2F,
  SHN_ChargedDeletableBuff = 0x30,
  SHN_MaxCnt = 0x31,
}