// Copyright © Spatial. All rights reserved.

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "selector",
  content: ["**/*.{js,jsx,ts,tsx}", "**/*/index.html", "!./**/node_modules"],
  plugins: [require("@headlessui/tailwindcss"), require("tailwindcss-animate")],
  theme: {
    colors: {
      transparent: "var(--color-base-transparent)",
      base: {
        neutral: {
          0: "var(--color-base-neutral-0)",
          1: "var(--color-base-neutral-1)",
          2: "var(--color-base-neutral-2)",
          3: "var(--color-base-neutral-3)",
          4: "var(--color-base-neutral-4)",
          5: "var(--color-base-neutral-5)",
          6: "var(--color-base-neutral-6)",
          7: "var(--color-base-neutral-7)",
          8: "var(--color-base-neutral-8)",
          9: "var(--color-base-neutral-9)",
        },
        blue: {
          0: "var(--color-base-blue-0)",
          1: "var(--color-base-blue-1)",
          2: "var(--color-base-blue-2)",
          3: "var(--color-base-blue-3)",
          4: "var(--color-base-blue-4)",
          5: "var(--color-base-blue-5)",
          6: "var(--color-base-blue-6)",
          7: "var(--color-base-blue-7)",
          8: "var(--color-base-blue-8)",
          9: "var(--color-base-blue-9)",
        },
        green: {
          0: "var(--color-base-green-0)",
          1: "var(--color-base-green-1)",
          2: "var(--color-base-green-2)",
          3: "var(--color-base-green-3)",
          4: "var(--color-base-green-4)",
          5: "var(--color-base-green-5)",
          6: "var(--color-base-green-6)",
          7: "var(--color-base-green-7)",
          8: "var(--color-base-green-8)",
          9: "var(--color-base-green-9)",
        },
        yellow: {
          0: "var(--color-base-yellow-0)",
          1: "var(--color-base-yellow-1)",
          2: "var(--color-base-yellow-2)",
          3: "var(--color-base-yellow-3)",
          4: "var(--color-base-yellow-4)",
          5: "var(--color-base-yellow-5)",
          6: "var(--color-base-yellow-6)",
          7: "var(--color-base-yellow-7)",
          8: "var(--color-base-yellow-8)",
          9: "var(--color-base-yellow-9)",
        },
        orange: {
          0: "var(--color-base-orange-0)",
          1: "var(--color-base-orange-1)",
          2: "var(--color-base-orange-2)",
          3: "var(--color-base-orange-3)",
          4: "var(--color-base-orange-4)",
          5: "var(--color-base-orange-5)",
          6: "var(--color-base-orange-6)",
          7: "var(--color-base-orange-7)",
          8: "var(--color-base-orange-8)",
          9: "var(--color-base-orange-9)",
        },
        red: {
          0: "var(--color-base-red-0)",
          1: "var(--color-base-red-1)",
          2: "var(--color-base-red-2)",
          3: "var(--color-base-red-3)",
          4: "var(--color-base-red-4)",
          5: "var(--color-base-red-5)",
          6: "var(--color-base-red-6)",
          7: "var(--color-base-red-7)",
          8: "var(--color-base-red-8)",
          9: "var(--color-base-red-9)",
        },
        purple: {
          0: "var(--color-base-purple-0)",
          1: "var(--color-base-purple-1)",
          2: "var(--color-base-purple-2)",
          3: "var(--color-base-purple-3)",
          4: "var(--color-base-purple-4)",
          5: "var(--color-base-purple-5)",
          6: "var(--color-base-purple-6)",
          7: "var(--color-base-purple-7)",
          8: "var(--color-base-purple-8)",
          9: "var(--color-base-purple-9)",
        },
        black: {
          0: "var(--color-base-black-0)",
          1: "var(--color-base-black-1)",
          2: "var(--color-base-black-2)",
          3: "var(--color-base-black-3)",
          4: "var(--color-base-black-4)",
          5: "var(--color-base-black-5)",
          6: "var(--color-base-black-6)",
          7: "var(--color-base-black-7)",
          8: "var(--color-base-black-8)",
          9: "var(--color-base-black-9)",
        },
        white: {
          0: "var(--color-base-white-0)",
          1: "var(--color-base-white-1)",
          2: "var(--color-base-white-2)",
          3: "var(--color-base-white-3)",
          4: "var(--color-base-white-4)",
          5: "var(--color-base-white-5)",
          6: "var(--color-base-white-6)",
          7: "var(--color-base-white-7)",
          8: "var(--color-base-white-8)",
          9: "var(--color-base-white-9)",
        },
      },
      background: {
        primary: "var(--color-background-primary)",
        secondary: "var(--color-background-secondary)",
        tertiary: "var(--color-background-tertiary)",
        quaternary: "var(--color-background-quaternary)",
        accent: "var(--color-background-accent)",
        overlay: "var(--color-background-overlay)",
        translucent: {
          primary: "var(--color-background-translucent-primary)",
        },
        inverted: {
          primary: "var(--color-background-inverted-primary)",
          secondary: "var(--color-background-inverted-secondary)",
          tertiary: "var(--color-background-inverted-tertiary)",
          quaternary: "var(--color-background-inverted-quaternary)",
        },
        control: {
          default: "var(--color-background-primary)",
          selected: {
            default: "var(--color-background-control-selected-default)",
            hover: "var(--color-background-control-selected-hover)",
            focus: "var(--color-background-control-selected-focus)",
            active: "var(--color-background-control-selected-active)",
          },
        },
        interactive: {
          primary: {
            default: "var(--color-background-interactive-primary-default)",
            hover: "var(--color-background-interactive-primary-hover)",
            focus: "var(--color-background-interactive-primary-focus)",
            active: "var(--color-background-interactive-primary-active)",
          },
          secondary: {
            default: "var(--color-background-interactive-secondary-default)",
            hover: "var(--color-background-interactive-secondary-hover)",
            focus: "var(--color-background-interactive-secondary-focus)",
            active: "var(--color-background-interactive-secondary-active)",
          },
          tertiary: {
            default: "var(--color-background-interactive-tertiary-default)",
            hover: "var(--color-background-interactive-tertiary-hover)",
            focus: "var(--color-background-interactive-tertiary-focus)",
            active: "var(--color-background-interactive-tertiary-active)",
          },
          outline: {
            default: "var(--color-background-interactive-outline-default)",
            hover: "var(--color-background-interactive-outline-hover)",
            focus: "var(--color-background-interactive-outline-focus)",
            active: "var(--color-background-interactive-outline-active)",
          },
          accent: {
            default: "var(--color-background-interactive-accent-default)",
            hover: "var(--color-background-interactive-accent-hover)",
            focus: "var(--color-background-interactive-accent-focus)",
            active: "var(--color-background-interactive-accent-active)",
          },
          information: {
            default: "var(--color-background-interactive-information-default)",
            hover: "var(--color-background-interactive-information-hover)",
            focus: "var(--color-background-interactive-information-focus)",
            active: "var(--color-background-interactive-information-active)",
          },
          success: {
            default: "var(--color-background-interactive-success-default)",
            hover: "var(--color-background-interactive-success-hover)",
            focus: "var(--color-background-interactive-success-focus)",
            active: "var(--color-background-interactive-success-active)",
          },
          attention: {
            default: "var(--color-background-interactive-attention-default)",
            hover: "var(--color-background-interactive-attention-hover)",
            focus: "var(--color-background-interactive-attention-focus)",
            active: "var(--color-background-interactive-attention-active)",
          },
          warning: {
            default: "var(--color-background-interactive-warning-default)",
            hover: "var(--color-background-interactive-warning-hover)",
            focus: "var(--color-background-interactive-warning-focus)",
            active: "var(--color-background-interactive-warning-active)",
          },
          danger: {
            default: "var(--color-background-interactive-danger-default)",
            hover: "var(--color-background-interactive-danger-hover)",
            focus: "var(--color-background-interactive-danger-focus)",
            active: "var(--color-background-interactive-danger-active)",
          },
          done: {
            default: "var(--color-background-interactive-done-default)",
            hover: "var(--color-background-interactive-done-hover)",
            focus: "var(--color-background-interactive-done-focus)",
            active: "var(--color-background-interactive-done-active)",
          },
        },
        severe: {
          information: "var(--color-background-severe-information)",
          success: "var(--color-background-severe-success)",
          attention: "var(--color-background-severe-attention)",
          warning: "var(--color-background-severe-warning)",
          danger: "var(--color-background-severe-danger)",
          done: "var(--color-background-severe-done)",
        },
      },
      foreground: {
        primary: "var(--color-foreground-primary)",
        secondary: "var(--color-foreground-secondary)",
        tertiary: "var(--color-foreground-tertiary)",
        quaternary: "var(--color-foreground-quaternary)",
        accent: "var(--color-foreground-accent)",
        inverted: {
          primary: "var(--color-foreground-inverted-primary)",
          secondary: "var(--color-foreground-inverted-secondary)",
          tertiary: "var(--color-foreground-inverted-tertiary)",
          quaternary: "var(--color-foreground-inverted-quaternary)",
        },
        severe: {
          information: "var(--color-foreground-severe-information)",
          success: "var(--color-foreground-severe-success)",
          attention: "var(--color-foreground-severe-attention)",
          warning: "var(--color-foreground-severe-warning)",
          danger: "var(--color-foreground-severe-danger)",
          done: "var(--color-foreground-severe-done)",
        },
        interactive: {
          default: "var(--color-foreground-interactive-default)",
          hover: "var(--color-foreground-interactive-hover)",
          focus: "var(--color-foreground-interactive-focus)",
          active: "var(--color-foreground-interactive-active)",
        },
      },
      border: {
        bounds: "var(--color-border-bounds)",
        divider: "var(--color-border-divider)",
        accent: "var(--color-border-accent)",
        interactive: {
          outline: {
            default: "var(--color-border-interactive-outline-default)",
            hover: "var(--color-border-interactive-outline-hover)",
            focus: "var(--color-border-interactive-outline-focus)",
            active: "var(--color-border-interactive-outline-active)",
          },
        },
        control: {
          default: "var(--color-border-control-default)",
          hover: "var(--color-border-control-hover)",
          focus: "var(--color-border-control-focus)",
          active: "var(--color-border-control-active)",
          selected: {
            default: "var(--color-border-control-selected-default)",
            hover: "var(--color-border-control-selected-hover)",
            focus: "var(--color-border-control-selected-focus)",
            active: "var(--color-border-control-selected-active)",
          },
        },
        severe: {
          information: "var(--color-border-severe-information)",
          success: "var(--color-border-severe-success)",
          attention: "var(--color-border-severe-attention)",
          warning: "var(--color-border-severe-warning)",
          danger: "var(--color-border-severe-danger)",
          done: "var(--color-border-severe-done)",
        },
      },
    },
    spacing: {
      full: "100%",
      0: "0px",
      "1/4u": "var(--unit-qt)",
      "1/2u": "var(--unit-hf)",
      "3/4u": "var(--unit-3qt)",
      "1u": "var(--unit-1)",
      "3/2u": "var(--unit-3hf)",
      "2u": "var(--unit-2)",
      "5/2u": "var(--unit-5hf)",
      "3u": "var(--unit-3)",
      "4u": "var(--unit-4)",
      "6u": "var(--unit-6)",
      "8u": "var(--unit-8)",
      "12u": "var(--unit-12)",
      "16u": "var(--unit-16)",
      "24u": "var(--unit-24)",
      "32u": "var(--unit-32)",
      "40u": "var(--unit-40)",
      "48u": "var(--unit-48)",
      "1/12": "calc(100% * (1 / 12))",
      "2/12": "calc(100% * (2 / 12))",
      "3/12": "calc(100% * (3 / 12))",
      "4/12": "calc(100% * (4 / 12))",
      "5/12": "calc(100% * (5 / 12))",
      "6/12": "calc(100% * (6 / 12))",
      "7/12": "calc(100% * (7 / 12))",
      "8/12": "calc(100% * (8 / 12))",
      "9/12": "calc(100% * (9 / 12))",
      "10/12": "calc(100% * (10 / 12))",
      "11/12": "calc(100% * (11 / 12))",
    },
    size: {
      full: "100%",
      auto: "auto",
      unset: "unset",
      0: "0px",
      "1/4u": "var(--unit-qt)",
      "1/2u": "var(--unit-hf)",
      "3/4u": "var(--unit-3qt)",
      "1u": "var(--unit-1)",
      "3/2u": "var(--unit-3hf)",
      "2u": "var(--unit-2)",
      "5/2u": "var(--unit-5hf)",
      "3u": "var(--unit-3)",
      "4u": "var(--unit-4)",
      "6u": "var(--unit-6)",
      "8u": "var(--unit-8)",
      "12u": "var(--unit-12)",
      "16u": "var(--unit-16)",
      "24u": "var(--unit-24)",
      "32u": "var(--unit-32)",
      "40u": "var(--unit-40)",
      "48u": "var(--unit-48)",
      "1/12": "calc(100% * (1 / 12))",
      "2/12": "calc(100% * (2 / 12))",
      "3/12": "calc(100% * (3 / 12))",
      "4/12": "calc(100% * (4 / 12))",
      "5/12": "calc(100% * (5 / 12))",
      "6/12": "calc(100% * (6 / 12))",
      "7/12": "calc(100% * (7 / 12))",
      "8/12": "calc(100% * (8 / 12))",
      "9/12": "calc(100% * (9 / 12))",
      "10/12": "calc(100% * (10 / 12))",
      "11/12": "calc(100% * (11 / 12))",
    },
    width: {
      full: "100%",
      screen: "100vw",
      fit: "fit-content",
      auto: "auto",
      unset: "unset",
      0: "0px",
      "1/4u": "var(--unit-qt)",
      "1/2u": "var(--unit-hf)",
      "3/4u": "var(--unit-3qt)",
      "1u": "var(--unit-1)",
      "3/2u": "var(--unit-3hf)",
      "2u": "var(--unit-2)",
      "5/2u": "var(--unit-5hf)",
      "3u": "var(--unit-3)",
      "4u": "var(--unit-4)",
      "6u": "var(--unit-6)",
      "8u": "var(--unit-8)",
      "12u": "var(--unit-12)",
      "16u": "var(--unit-16)",
      "24u": "var(--unit-24)",
      "32u": "var(--unit-32)",
      "40u": "var(--unit-40)",
      "48u": "var(--unit-48)",
      "1/12": "calc(100% * (1 / 12))",
      "2/12": "calc(100% * (2 / 12))",
      "3/12": "calc(100% * (3 / 12))",
      "4/12": "calc(100% * (4 / 12))",
      "5/12": "calc(100% * (5 / 12))",
      "6/12": "calc(100% * (6 / 12))",
      "7/12": "calc(100% * (7 / 12))",
      "8/12": "calc(100% * (8 / 12))",
      "9/12": "calc(100% * (9 / 12))",
      "10/12": "calc(100% * (10 / 12))",
      "11/12": "calc(100% * (11 / 12))",
    },
    height: {
      full: "100%",
      screen: "100vh",
      fit: "fit-content",
      auto: "auto",
      unset: "unset",
      0: "0px",
      "1/4u": "var(--unit-qt)",
      "1/2u": "var(--unit-hf)",
      "3/4u": "var(--unit-3qt)",
      "1u": "var(--unit-1)",
      "3/2u": "var(--unit-3hf)",
      "2u": "var(--unit-2)",
      "5/2u": "var(--unit-5hf)",
      "3u": "var(--unit-3)",
      "4u": "var(--unit-4)",
      "6u": "var(--unit-6)",
      "8u": "var(--unit-8)",
      "12u": "var(--unit-12)",
      "16u": "var(--unit-16)",
      "24u": "var(--unit-24)",
      "32u": "var(--unit-32)",
      "40u": "var(--unit-40)",
      "48u": "var(--unit-48)",
      "1/12": "calc(100% * (1 / 12))",
      "2/12": "calc(100% * (2 / 12))",
      "3/12": "calc(100% * (3 / 12))",
      "4/12": "calc(100% * (4 / 12))",
      "5/12": "calc(100% * (5 / 12))",
      "6/12": "calc(100% * (6 / 12))",
      "7/12": "calc(100% * (7 / 12))",
      "8/12": "calc(100% * (8 / 12))",
      "9/12": "calc(100% * (9 / 12))",
      "10/12": "calc(100% * (10 / 12))",
      "11/12": "calc(100% * (11 / 12))",
    },
    fontFamily: {
      sans: ["Oxygen", "sans-serif"],
      mono: ["Oxygen Mono", "monospace"],
    },
    fontSize: {
      inherit: "inherit",
      xs: ["8px", "12px"],
      s: ["12px", "20px"],
      m: ["16px", "24px"],
      l: ["20px", "32px"],
      xl: ["24px", "36px"],
      "2xl": ["32px", "52px"],
      "3xl": ["40px", "64px"],
      "4xl": ["48px", "72px"],
      "5xl": ["64px", "96px"],
    },
    fontWeight: {
      light: "300",
      regular: "400",
      bold: "700",
    },
    borderRadius: {
      none: "0",
      inherit: "inherit",
      "1/4u": "var(--unit-qt)",
      "1/2u": "var(--unit-hf)",
      "3/4u": "var(--unit-3qt)",
      "1u": "var(--unit-1)",
      "3/2u": "var(--unit-3hf)",
      "2u": "var(--unit-2)",
      full: "9999px",
    },
    extend: {
      keyframes: {
        reveal: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        grow: {
          from: { opacity: 0, transform: "scale(0.95)" },
          to: { opacity: 1, transform: "scale(1.0)" },
        },
        vanish: {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        shrink: {
          from: { opacity: 1, transform: "scale(1.0)" },
          to: { opacity: 0, transform: "scale(0.95)" },
        },
        "dialog-in": {
          from: {
            opacity: "0",
            transform: "translate(-50%, -48%) scale(0.95)",
          },
          to: { opacity: "1", transform: "translate(-50%, -50%) scale(1)" },
        },
        "dialog-out": {
          from: { opacity: "1", transform: "translate(-50%, -50%) scale(1)" },
          to: {
            opacity: "0",
            transform: "translate(-50%, -48%) scale(0.95)",
          },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
      },
      animation: {
        reveal: "reveal 200ms cubic-bezier(0.16, 1, 0.3, 1)",
        grow: "grow 200ms cubic-bezier(0.16, 1, 0.3, 1)",
        vanish: "vanish 200ms cubic-bezier(0.16, 1, 0.3, 1)",
        shrink: "shrink 200ms cubic-bezier(0.16, 1, 0.3, 1)",
        "dialog-in": "dialog-in 200ms cubic-bezier(0.16, 1, 0.3, 1)",
        "dialog-out": "dialog-out 200ms cubic-bezier(0.16, 1, 0.3, 1)",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
      },
    },
  },
};
