name: Publish

on:
  push:
    tags:
      - "spatial-cloud*"
      - "spatial-interface-data*"
      - "spatial-interface-design*"
      - "spatial-interface-client*"

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'spatial-cloud')
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.x"

      - name: Restore
        run: dotnet restore packages/cloud/Core/Spatial.csproj

      - name: Package
        run: dotnet pack packages/cloud/Core/Spatial.csproj -c Release -o ./nupkg

      - name: Publish
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --skip-duplicate
