name: QA

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore
        working-directory: cloud
        run: dotnet restore

      - name: Build
        working-directory: cloud
        run: dotnet build -c Release

      - name: Test
        working-directory: cloud
        run: dotnet test -c Release --verbosity normal